name: Swift

env:
  TARGET: Testando Fastlane
  XCODE_WORKSPACE: Testando Fastlane.xcworkspace
  SIMULATOR: iPhone 11

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode 13.4
        run: sudo xcode-select -switch /Applications/Xcode_13.4.app

      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: testflight
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: '${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}'
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'